# Start from the official Fedora 44 Kinoite OCI image
FROM quay.io/fedora/fedora-kinoite:44

# Since we're using bootc, we use standard dnf commands

# External repos go here, set dnf repo cache merely as cache
RUN --mount=type=cache,target=/var/cache/libdnf5,sharing=locked \
    --mount=type=cache,target=/var/lib/dnf,sharing=locked \
    dnf -y --refresh install \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
# Removals and swaps
    dnf -y remove \
    krfb \
    kjournald \
    kdebugsettings \
    kde-connect \
    kcharselect \
    kfind && \
    dnf -y swap toolbox distrobox --allowerasing && \
    dnf -y swap kde-partitionmanager gparted --allowerasing && \
# Multimedia, codecs, drivers, you can add rocm if ever need
    dnf -y swap ffmpeg-free ffmpeg --allowerasing && \
    dnf -y install --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin @multimedia && \
    dnf -y install \
    mesa-va-drivers-freeworld \
    #pipewire-codec-aptx \ now comes by default
    mozilla-openh264 \
# Add-ons - need all recommended packages
    virt-manager libayatana-appindicator-gtk3 \
    btrfs-assistant && \
# Themes, fonts and setup for custom copy weakdeps disabled where possible
    dnf install -y --setopt="install_weak_deps=False" \
    plasma-oxygen oxygen-cursor-themes oxygen-sounds oxygen-fonts \
    cjkuni-ukai-fonts cjkuni-uming-fonts \
    filezilla \
    #impallari-raleway-fonts \ no longer needed
    jetbrains-mono-fonts \
    podman-compose podman-docker \
    k3b cdrskin \
    btop \
    tailscale \
    trash-cli && \
    rm -rf /var/tmp/* /tmp/*
#mkdir -p /usr/share/fonts/{jigmo,buckeye-sans,buckeye-serif}-fonts

# Copy custom fonts / Jigmo for Chinese, Buckeye for OSU purposes
COPY ./Jigmo/*.ttf /usr/share/fonts/jigmo-fonts/
COPY ./BuckeyeSans/*.otf /usr/share/fonts/buckeye-sans-fonts/
COPY ./BuckeyeSerif/*.otf /usr/share/fonts/buckeye-serif-fonts/

# Font setup, service setup, base-system default /etc changes
RUN fc-cache -f /usr/share/fonts/{jigmo,buckeye-{sans,serif}}-fonts && \
    systemctl enable tailscaled.service && \
    systemctl mask sshd.socket sshd.service && \
    touch /etc/containers/nodocker && \
    echo "XMODIFIERS=@im=fcitx" >> /etc/environment && \
    echo "export XMODIFIERS=@im=fcitx" > /etc/profile.d/fcitx.sh

# Important: Label the image as bootc-compatible
LABEL containers.bootc=1
