# Start from the official Fedora 44 Kinoite OCI image
FROM quay.io/fedora/fedora-kinoite:44

# Add your custom packages
# Since we're using bootc, we use standard dnf commands

# Add repos here before install, for example, vscodium/vscode
RUN tee /etc/yum.repos.d/vscodium.repo << 'EOF'
[gitlab.com_paulcarroty_vscodium_repo]
name=gitlab.com_paulcarroty_vscodium_repo
baseurl=https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
metadata_expire=1h
EOF

# Your 'overlay' packages go here, including rpmfusion, removals/overrides, etc.
# Cache cleanup is good because why write things that won't be useful?

# Removals
RUN dnf -y remove \
    krfb \
    kjournald \
    kdebugsettings \
    kde-partitionmanager \
    kde-connect \
    kcharselect \
    kfind && \
    dnf -y clean all

# RPM fusion and drivers, codecs, and other base-system overrides -- non-free rpmfusion could also be put in the first line
# Notably, we include the mesa-drivers for AMD setups (not strictly needed) and pipewire aptx codec for bluetooth, besides standard ffmpeg swap and further multimedia install
# ** Note: Forced url for rpmfusion to match release of 44 to prevent bugs/out-of-sync issues since this is a pre-release (the default is: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm) -- when it's released we will build with this original, recommended URL
# ** Note: we install the mozilla-openh264 from F43 to have a working Firefox openh264 plugin, will be fixed soon
# ** Note: the default image doesn't include the @multimedia group so we manually install rather than using rpmfusion's recommendation to update the group
RUN dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-44.noarch.rpm && \
    dnf -y swap toolbox distrobox --allowerasing && \
    dnf -y install \
    mesa-va-drivers-freeworld \
    pipewire-codec-aptx && \
    dnf -y swap ffmpeg-free ffmpeg --allowerasing && \
    dnf -y install @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin && \
    dnf -y install mozilla-openh264 --releasever=43 && \
    dnf -y clean all

# Additional apps (GUI, etc.), weak dependencies disabled except where useful
# The section for weak dependencies could be removed and all folded into the regular install (where gparted is) if you don't care about cleaning weak deps
RUN dnf -y install \
    virt-manager libayatana-appindicator-gtk3 \
    gparted \
    btrfs-assistant && \
    dnf -y install --setopt=install_weak_deps=False \
    podman-compose podman-docker \
    k3b cdrskin \
    cjkuni-ukai-fonts cjkuni-uming-fonts jetbrains-mono-fonts \
    btop \
    tailscale \
    codium \
    trash-cli \
    micro vim \
    java-devel && \
    dnf -y clean all

# Custom services or none at all can go here as Fedora default-enables most.
# Here I use my preference to secure sshd by default-disabling and enable tailscale :D
RUN systemctl enable tailscaled.service && \
    systemctl mask sshd.socket sshd.service

# Here you can run any image-layer-level /etc overrides. Useful if you don't want to have to think about these ever
# For example, if needed, can set locale.conf with a default val: echo "LANG=\"en_US.UTF-8\"" > /etc/locale.conf
# In general, not usually necessary for most people, but YMMV. You can always do these configs manually!
RUN touch /etc/containers/nodocker && \
    echo "XMODIFIERS=@im=fcitx" >> /etc/environment && \
    echo "export XMODIFIERS=@im=fcitx" > /etc/profile.d/fcitx.sh

# Important: Label the image as bootc-compatible
LABEL containers.bootc=1
